"""Create the club and accumulated stats tables

Revision ID: 4b41e4ac673f
Revises: 
Create Date: 2026-09-10 20:56:18.474465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b41e4ac673f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('abbr', sa.String(), nullable=True),
    sa.Column('stadium_name', sa.String(), nullable=True),
    sa.Column('stadium_city', sa.String(), nullable=True),
    sa.Column('stadium_country', sa.String(), nullable=True),
    sa.Column('stadium_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_pass', sa.Integer(), nullable=False),
    sa.Column('accurate_pass', sa.Integer(), nullable=False),
    sa.Column('total_long_balls', sa.Integer(), nullable=False),
    sa.Column('accurate_long_balls', sa.Integer(), nullable=False),
    sa.Column('accurate_own_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_own_half_passes', sa.Integer(), nullable=False),
    sa.Column('accurate_opposition_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_opposition_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_clearance', sa.Integer(), nullable=False),
    sa.Column('ball_recovery', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('punches', sa.Integer(), nullable=False),
    sa.Column('total_keeper_sweeper', sa.Integer(), nullable=False),
    sa.Column('accurate_keeper_sweeper', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('possession_lost_ctrl', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('goal_assist', sa.Integer(), nullable=False),
    sa.Column('total_cross', sa.Integer(), nullable=False),
    sa.Column('accurate_cross', sa.Integer(), nullable=False),
    sa.Column('aerial_lost', sa.Integer(), nullable=False),
    sa.Column('duel_lost', sa.Integer(), nullable=False),
    sa.Column('duel_won', sa.Integer(), nullable=False),
    sa.Column('challenge_lost', sa.Integer(), nullable=False),
    sa.Column('total_contest', sa.Integer(), nullable=False),
    sa.Column('won_contest', sa.Integer(), nullable=False),
    sa.Column('total_tackle', sa.Integer(), nullable=False),
    sa.Column('was_fouled', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('key_pass', sa.Integer(), nullable=False),
    sa.Column('on_target_scoring_attempt', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('outfielder_block', sa.Integer(), nullable=False),
    sa.Column('blocked_scoring_attempt', sa.Integer(), nullable=False),
    sa.Column('interception_won', sa.Integer(), nullable=False),
    sa.Column('big_chance_created', sa.Integer(), nullable=False),
    sa.Column('big_chance_missed', sa.Integer(), nullable=False),
    sa.Column('dispossessed', sa.Integer(), nullable=False),
    sa.Column('shot_off_target', sa.Integer(), nullable=False),
    sa.Column('unsuccessful_touch', sa.Integer(), nullable=False),
    sa.Column('total_offside', sa.Integer(), nullable=False),
    sa.Column('good_high_claim', sa.Integer(), nullable=False),
    sa.Column('saved_shots_from_inside_the_box', sa.Integer(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('total_ball_carries_distance', sa.Float(), nullable=False),
    sa.Column('ball_carries_count', sa.Integer(), nullable=False),
    sa.Column('total_progression', sa.Float(), nullable=False),
    sa.Column('progressive_ball_carries_count', sa.Integer(), nullable=False),
    sa.Column('keeper_save_value', sa.Float(), nullable=False),
    sa.Column('goals_prevented', sa.Float(), nullable=False),
    sa.Column('pass_value_normalized', sa.Float(), nullable=False),
    sa.Column('dribble_value_normalized', sa.Float(), nullable=False),
    sa.Column('defensive_value_normalized', sa.Float(), nullable=False),
    sa.Column('goalkeeper_value_normalized', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('club')
    # ### end Alembic commands ###
