"""Rename player_stats to acc_player_stats

Revision ID: 98b0939c1019
Revises: 4b41e4ac673f
Create Date: 2026-09-10 21:09:13.133248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b0939c1019'
down_revision: Union[str, Sequence[str], None] = '4b41e4ac673f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_pass', sa.Integer(), nullable=False),
    sa.Column('accurate_pass', sa.Integer(), nullable=False),
    sa.Column('total_long_balls', sa.Integer(), nullable=False),
    sa.Column('accurate_long_balls', sa.Integer(), nullable=False),
    sa.Column('accurate_own_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_own_half_passes', sa.Integer(), nullable=False),
    sa.Column('accurate_opposition_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_opposition_half_passes', sa.Integer(), nullable=False),
    sa.Column('total_clearance', sa.Integer(), nullable=False),
    sa.Column('ball_recovery', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('punches', sa.Integer(), nullable=False),
    sa.Column('total_keeper_sweeper', sa.Integer(), nullable=False),
    sa.Column('accurate_keeper_sweeper', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('possession_lost_ctrl', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('goal_assist', sa.Integer(), nullable=False),
    sa.Column('total_cross', sa.Integer(), nullable=False),
    sa.Column('accurate_cross', sa.Integer(), nullable=False),
    sa.Column('aerial_lost', sa.Integer(), nullable=False),
    sa.Column('duel_lost', sa.Integer(), nullable=False),
    sa.Column('duel_won', sa.Integer(), nullable=False),
    sa.Column('challenge_lost', sa.Integer(), nullable=False),
    sa.Column('total_contest', sa.Integer(), nullable=False),
    sa.Column('won_contest', sa.Integer(), nullable=False),
    sa.Column('total_tackle', sa.Integer(), nullable=False),
    sa.Column('was_fouled', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('key_pass', sa.Integer(), nullable=False),
    sa.Column('on_target_scoring_attempt', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('outfielder_block', sa.Integer(), nullable=False),
    sa.Column('blocked_scoring_attempt', sa.Integer(), nullable=False),
    sa.Column('interception_won', sa.Integer(), nullable=False),
    sa.Column('big_chance_created', sa.Integer(), nullable=False),
    sa.Column('big_chance_missed', sa.Integer(), nullable=False),
    sa.Column('dispossessed', sa.Integer(), nullable=False),
    sa.Column('shot_off_target', sa.Integer(), nullable=False),
    sa.Column('unsuccessful_touch', sa.Integer(), nullable=False),
    sa.Column('total_offside', sa.Integer(), nullable=False),
    sa.Column('good_high_claim', sa.Integer(), nullable=False),
    sa.Column('saved_shots_from_inside_the_box', sa.Integer(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('total_ball_carries_distance', sa.Float(), nullable=False),
    sa.Column('ball_carries_count', sa.Integer(), nullable=False),
    sa.Column('total_progression', sa.Float(), nullable=False),
    sa.Column('progressive_ball_carries_count', sa.Integer(), nullable=False),
    sa.Column('keeper_save_value', sa.Float(), nullable=False),
    sa.Column('goals_prevented', sa.Float(), nullable=False),
    sa.Column('pass_value_normalized', sa.Float(), nullable=False),
    sa.Column('dribble_value_normalized', sa.Float(), nullable=False),
    sa.Column('defensive_value_normalized', sa.Float(), nullable=False),
    sa.Column('goalkeeper_value_normalized', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_pass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_pass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_long_balls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_long_balls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_own_half_passes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_own_half_passes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_opposition_half_passes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_opposition_half_passes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_clearance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ball_recovery', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('punches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_keeper_sweeper', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_keeper_sweeper', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minutes_played', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('touches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('possession_lost_ctrl', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_assist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cross', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accurate_cross', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aerial_lost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duel_lost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duel_won', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('challenge_lost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_contest', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('won_contest', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tackle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('was_fouled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_pass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('on_target_scoring_attempt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outfielder_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_scoring_attempt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interception_won', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('big_chance_created', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('big_chance_missed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dispossessed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shot_off_target', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unsuccessful_touch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_offside', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('good_high_claim', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saved_shots_from_inside_the_box', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expected_assists', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_ball_carries_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ball_carries_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_progression', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('progressive_ball_carries_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keeper_save_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('goals_prevented', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pass_value_normalized', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dribble_value_normalized', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('defensive_value_normalized', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('goalkeeper_value_normalized', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('player_stats_pkey'))
    )
    op.drop_table('acc_player_stats')
    # ### end Alembic commands ###
