"""Insert the composite key

Revision ID: fc8554a76ca2
Revises: 98b0939c1019
Create Date: 2026-09-10 21:40:11.673237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8554a76ca2'
down_revision: Union[str, Sequence[str], None] = '98b0939c1019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_player_stats', sa.Column('player_id', sa.Integer(), nullable=False))
    op.drop_column('acc_player_stats', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_player_stats', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('acc_player_stats', 'player_id')
    # ### end Alembic commands ###
